name: pulseplay
description: A cross-platform music app built with Flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.0.5
  path_provider: ^2.0.14
  sqflite: ^2.2.0+2
  just_audio: ^0.9.30
  flutter_spinkit: ^5.1.0
  cached_network_image: ^3.2.3
  window_manager: ^0.4.3
  file_picker: ^8.1.5
  audio_service: ^0.18.10
  flutter_launcher_icons: ^0.14.2
  flutter_riverpod: ^2.3.6
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.7
  youtube_explode_dart: ^2.3.6
  logger: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true